### ISSUE TITLE
FileProvider problem

### ISSUE THREAD

**Issue by onefreddy** [b12kab/DownloadTwo#1]
Hey! Thanks for the great example! There is absolutely no information on the Internet on this issue for xamarin. You helped me a lot to figure it out) But I ran into a new problem, now FileProvider does not work for me. 
Could you expand the example so that there is a button "open file" and then through the FileProvider you can choose in which application to open it?

**Comment by onefreddy** [comment]
im using this code:

```
                var downloads = Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDownloads);
                string filePath = System.IO.Path.Combine(downloads.CanonicalPath, filename);
                var jFile = new Java.IO.File(filePath);
                //var jUri = Android.Net.Uri.FromFile(jFile);
                var jUri = FileProvider.GetUriForFile(Application.Context, Application.Context.PackageName + ".fileprovider", jFile);
                string mimeType = MimeMapping.MimeUtility.GetMimeMapping(filename);

                Intent intent = new Intent();
                intent.AddFlags(ActivityFlags.ClearWhenTaskReset);
                intent.AddFlags(ActivityFlags.NewTask);
                intent.AddFlags(ActivityFlags.GrantReadUriPermission);
                intent.SetAction(Intent.ActionView);
                intent.SetDataAndType(jUri, mimeType);
                act.StartActivity(intent);
```

error: File not found (although I know that the file exists at the given path)

**Comment by b12kab** [comment]
> There is absolutely no information on the Internet on this issue for xamarin. You helped me a lot to figure it out) But I ran into a new problem, now FileProvider does not work for me.
> Could you expand the example so that there is a button "open file" and then through the FileProvider you can choose in which application to open it?

Hi,

What you have in your code example above is similar to my API 28. I've not personally used FileProvider, but based on my tests in [my MediaStore article  #3](https://keithbeattyblog.wordpress.com/2021/12/26/using-xamarin-android-with-mediastore-part-3/), I don't think that this will work - at all. 

The reason for this is that the file won't be readable by the app, unless the destination app itself opens the file via [Storage Access Framework](https://android-doc.github.io/guide/topics/providers/document-provider.html) - it won't be able to read the file, as it won't be granted permission to the file by Android.

Best of luck.
